# Generated by Django 5.0.3 on 2024-03-14 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('battery_level', models.FloatField()),
                ('current_location', models.CharField(max_length=100)),
                ('last_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
